# 支付宝
alipay:
  app_id: 2016101800716012
  merchant_private_key:                                       #自己的私钥
  alipay_public_key:                                          #支付宝公钥
  notify_url: http://5mjyk4ygtg.52http.tech/pay/success      # 回调页面
  gatewayUrl: https://openapi.alipaydev.com/gateway.do
  sign_type: RSA2
  charset: utf-8
  return_url: http://ppr3hihbp3.54http.tech/pay/payTest


spring:
  redis:
    host: 192.168.226.128
    port: 6379
    database: 2
  rabbitmq:  # rabiit
    host: 47.114.37.22
    port: 5672
    virtual-host: /lichen
    username: anda
    password: anda
    listener:
      simple:
        prefetch: 1
        acknowledge-mode: manual

# 线程池
thread:
  pool:
    coreSize: 100
    maxSize: 500
    keepAliveTime: 60
    queueSize: 1000
