# 支付宝
alipay:
  app_id: 2016101800716012
  merchant_private_key: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQClsN9slZsqoHThprC7yhSIr49DkR4MrvLnCX2kzp+SKDLkQWayktH4moXEeEsk+Kp84pqKqJfxho78GJt0TuTL/OxZgt42VUPdINLxcCfSDUDOx8q8ltozR7xGX0rRCZooHasjeX/UMzyeupoo5xyWfk/LjQsFOf4hsAR6xbQgey3wCLc0Wo+dYN3PHWZ4KDfEnvBUZg4Mb6TBOHpPiD/C8LL3cFdZ1IHKbKY4yUIBlW5B6rd5xoGqBVbQt6F2htg33mmm+nY5xNFZ5EFicZa9g/rgkISdk/DIcGFZCSWVe+qzcK7vq6RJXktHKzUt+6ZOuIEaQ5IpTFRYC4gyBY/dAgMBAAECggEBAKGLbnq27p9D7FFprRyarSSLTroIzex90lQR+89oqUneKahEX7Wx0kh5l/xzcIhubgLvCNAyClqw383IzCA9H3QHeATZxH/i6BS8AQ7nU9vHki1JvE/dIIco5NcT56UhoIyGSKqAtnIVNoBn3RAOLOBJ7NDABkOlRDJiJCvzgGi9OD9srHwX9CTLBxz2CIXdJDKq4SZAWOChEzYw+oh+RqK7lstC42RzZ3s4nS/gFSBFCuiyP/QBrrwddJkeceTlnCtTiMg5rii0y58i7FeR1uEQcy4FD34RqZo02F6Q/ZDKbUUwRlufhu3utf4wTB6VrcbMK1npWrkYjJiPjOYb7OECgYEA9zFgAUD/Rx4DzwW/6RA0B9zKmhlsCwlTzC26mEu7HdlbMzonV2vHKyBbptFWUpdPg735kmmanuNiKzjOVEKYVoRqTdjjeH31x3KZ/B/1H0jy4MbE9OpijYDAZiLInrrKwe8H+cryIH3RK7wD+hko4EbYbxS0XNln+aU8gzZZt/kCgYEAq5ggFU4UsVCyGl6IXWxKSRMpsefH3dYe3Q3lXdQGcbZ8HrpVa81ZKSwv+14d6xtWX7R90Qr9EUmfmQHXdfeTlor0HDTmw5UeYIbz8RMCUfvBS2b4bGkhDQODDPmQoI1wkjC/yya6dUgsWxRszTBfWrdVeIKlWW6yTY+WX9zauAUCgYEAnXv2dzYKrSthL86w8nIhQ/UVmtGhdPKPUaC8pXRyFNU6dkuRbu+6Zy5pVcE+psXBoeQxkWb4XEvvaiv5v9LhrRUViN0qJsTRBi1sDyXpC/J00mGwb3y4JwClEy0L9Zx5us5nnWv/kFW4Io3ZVsgas7BPCY3+Tr0vsevkvo+s3zkCgYByDLduUapRPEhUXHaYWYx6S2FQHLTsDhAPbtf/aBgsZlTS+5ghAah8RCFUGncaN95N2CIz2fDgF6YbRW0WvEn9Kjgbs1GZtzgsgiYLGk5VfVY5LqR5MdrE0ou9CPcGr1ud3wbrGL+fiivpEYdLThZiri4B3hvWeEvMX15cMuewnQKBgE4899QWKeibTopwLtnl9bJHVxIYiORIeJWKYzVqhscFiEsYY/yvyU72dggW4uVCpM+YFrkaUjAdWL9Is3tr/uB8qarmNiZloEEwo1Pq4/7YTOQsJn6qOP/3SqpFBcVMwfQYBIbvupJsXd0Ke0v5mI960Fv9Yy9J+v1trZURdAN/
  alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApgO6rIJNBTsEyEQYQSnrwwVg8g9MxuPlar58wM25Lu0YyAUzc5Z4cle42R1dXf0ytS0Dr9qqhUYqYt3dDvaPEQk1nIGthSvnSPH1kqPMvtqFXZe0X3FQdMrfqEgOwGwoVDcup5t8kKRSbIOW3GU0GqVkvWRaamMn6ulpH4IAW8FwBk+47Gq3BEVmhhOUWWfFtGed88TinflKYzj9TSXordEPIBXkM9a9DhMUrwmoMi3hedQvrhYbvo0Gt6teai5sfnAm6hIVl2DrjCNJDZ6KshM7piuZ9upABEARx/WGWzSLnuM1EUrkZX2h3LIEFYkFl7EyGibLzhayV2UQkcZaAQIDAQAB
  notify_url: http://5mjyk4ygtg.52http.tech/pay/success      # 回调页面
  gatewayUrl: https://openapi.alipaydev.com/gateway.do
  sign_type: RSA2
  charset: utf-8
  return_url: http://ppr3hihbp3.54http.tech/pay/payTest


spring:
  redis:
    host: 192.168.226.128
    port: 6379
    database: 2
  rabbitmq:  # rabiit
    host: 47.114.37.22
    port: 5672
    virtual-host: /lichen
    username: anda
    password: anda
    listener:
      simple:
        prefetch: 1
        acknowledge-mode: manual

# 线程池
thread:
  pool:
    coreSize: 100
    maxSize: 500
    keepAliveTime: 60
    queueSize: 1000